name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - name: cleanup
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: .
        clean: .
    - uses: actions/checkout@main
    - uses: actions/setup-python@v2 
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme myst_parser
    - name: sphinx build
      run: |
        sphinx-build . docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/